export enum PlaybackAction {
  START_JAM = 'START_JAM',
  STOP_JAM = 'STOP_JAM',
  START_SONG = 'START_SONG',
  PAUSE_SONG = 'PAUSE_SONG',
  RESUME_SONG = 'RESUME_SONG',
  SKIP_SONG = 'SKIP_SONG',
  PREVIOUS_SONG = 'PREVIOUS_SONG',
  REORDER_QUEUE = 'REORDER_QUEUE',
}
